- ignore: { name: "Eta reduce" }
- ignore: { name: "Avoid lambda" }
- ignore: { name: "Avoid lambda using `infix`" }
- ignore: { name: "Use const" }
- ignore: { name: "Use and" }
- ignore: { name: "Use all" }
- ignore: { name: "Fuse foldr/map" }
- ignore: { name: "Evaluate" }
